# Generated by Django 5.2.9 on 2026-01-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_is_active_member_membership_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_end_date',
            field=models.DateField(),
        ),
    ]
