# Generated by Django 5.2.9 on 2026-01-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_dob_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='member',
            name='fees_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fees Amount'),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID'),
        ),
    ]
